# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 2.7'

gem "octokit", "~> 4.0"
gem 'travis'
gem 'faraday'
gem 'faraday_middleware'
gem 'pry-byebug'

